---
#---------------------------------#
#  Build Image                    #
#---------------------------------#
image: Visual Studio 2022

#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
    - ps: .\build.ps1 --target=CI

#---------------------------------#
# Tests
#---------------------------------#
test: off

#---------------------------------#
#  Pull Requests                  #
#---------------------------------#
pull_requests:
  do_not_increment_build_number: true

#---------------------------------#
#  General                        #
#---------------------------------#
skip_branch_with_pr: true

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
    # Whitelist
    only:
        - develop
        - master
        - /release\/.*/
        - /hotfix\/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
    - Tools -> recipe.cake